fixes #781 by setting a new default color for satellite and dark
mapbox/geojson.io pull request #794
Opened 2022-11-23 08:39 UTC by DJFriar

I tested a bunch of different colors and this was one of the easier ones to see on the satellite base map, while also still looking good on the dark base map.

For simplicity I just changed the value but it would be easy enough to make this only apply to the Satellite base map and leave the Dark alone if that is the preference.

2022-11-23 14:42 UTC, chriswhong commented
Hi, thanks so much for working on this.  I checked out your branch and still think this color doesn't contrast enough with the features in the satellite style, especially when looking at an urban area:

<img width="1045" alt="geojson_io___powered_by_Mapbox" src="https://user-images.githubusercontent.com/1833820/203574002-69c6f76a-0684-413d-9f70-a2051703eb6d.png">

At the very least I would suggest we come up with a special color just for satellite that provides good contrast most of the time.  Would you be able to re-work this and try to find a good color, then make sure it's only applied to the satellite-streets style?

Also I haven't checked but we should also make sure the markers are getting these colors when we switch to the different styles.

2022-11-23 15:03 UTC, chriswhong commented
<img width="1064" alt="geojson_io___powered_by_Mapbox" src="https://user-images.githubusercontent.com/1833820/203577863-904824ae-1fbf-43d1-86df-2917b97afa22.png">

Disregard my previous comment!  I didn't build the bundle.  We don't have a separate build step, so can you please commit `dist/site.js` to your branch?  (I have some plans for a separate build step in the works, but it's not ready yet)

I don't have strong opinions on this purple and think it solves the immediate problem.  I've opened #796 as a new issue to address the mismatch between marker colors and line/polygon colors.

If you would be interested in attacking #796 in this PR as well that would be great.  If not, no worries, we can merge this and work on the other issue separately.

2022-11-23 15:12 UTC, chriswhong commented
If it's not too much to ask, I would suggest we use the purple for satellite and OSM.  So leave `LIGHT_FEATURE_COLOR` as it was before and add a new `PURPLE_FEATURE_COLOR` constant and the logic to apply it to those two styles.

2022-11-24 02:01 UTC, DJFriar commented
> If it's not too much to ask, I would suggest we use the purple for satellite and OSM. So leave `LIGHT_FEATURE_COLOR` as it was before and add a new `PURPLE_FEATURE_COLOR` constant and the logic to apply it to those two styles.

This has been completed and checked in. The latest commit also fixes #796.

2022-11-24 03:34 UTC, chriswhong requested changes

2022-11-24 03:34 UTC, chriswhong commented on src/ui/map/util.js
> +    console.log(`color is ${color}`);
Stray console log

2022-11-24 03:34 UTC, chriswhong commented on src/ui/map/util.js
> +    // Update the dot in the Marker for Dark base map style
Nice touch!

2022-11-24 03:34 UTC, chriswhong commented on src/constants.js
> +  DEFAULT_PURPLE_FEATURE_COLOR: '#ff40ff'
Glad we moved these here!

2022-11-24 03:38 UTC, chriswhong commented
Looks great and works great, just saw one stray `console.log` that should be removed. 

BTW there is now a #geojson-dot-io channel in the MapboxDevs discord if you are interested. May be helpful if you need clarification on future issues you want to work on.  https://discord.gg/uMpcC5RmJh

2022-11-24 08:53 UTC, DJFriar commented
> Looks great and works great, just saw one stray `console.log` that should be removed.

I have checked in an update to remove that console.log (and another I found as well). I changed the color from purple to bright green because when I read the email I saw the first message you sent and thought it was about the purple. Anyway, it is green now, but let me know if you prefer the purple and I can change it real quick.

> BTW there is now a #geojson-dot-io channel in the MapboxDevs discord if you are interested. May be helpful if you need clarification on future issues you want to work on. https://discord.gg/uMpcC5RmJh

I joined there just after I made the earlier commit actually. I am also DJFriar there.

2022-11-25 02:28 UTC, chriswhong approved these changes

2022-11-25 02:29 UTC, chriswhong commented
The green looks great!  Thanks for this!

2022-11-25 02:30 UTC, merged